### ISSUE TITLE
Testplan for all API xmlrpc methods

### ISSUE THREAD

**Issue by netzulo** [TestLinkOpenSourceTRMS/testlink-tests#3]
# Description

- Updated package to Pypi package manager : https://pypi.org/project/testlinktests

## TODOs

+ [ ] create request: ``TPROJECT_CREATE = 'tl.createTestProject'``
+ [ ] create request: ``TPLAN_CREATE = 'tl.createTestPlan'``
+ [ ] create request: ``TPLAN_ADD_TCASE = 'tl.addTestCaseToTestPlan'``
+ [ ] create request: ``TPLAN_EXEC_LATEST = 'tl.getLastExecutionResult'``
+ [ ] create request: ``BUILD_CREATE = 'tl.createBuild'``
+ [ ] create request: ``TSUITE_CREATE = 'tl.createTestSuite'``
+ [ ] create request: ``TSUITE_TCASES = 'tl.getTestCasesForTestSuite'``
+ [ ] create request: ``REQ_ASSIGN = 'tl.assignRequirements'``
+ [ ] create request: ``TCASE_CREATE = 'tl.createTestCase'``
+ [ ] create request: ``TCASE_ATTACHMENTS = 'tl.getTestCaseAttachments'``
+ [ ] create request: ``TCASE_CUSTOM_FIELD_DESIGN_VALUE = 'tl.getTestCaseCustomFieldDesignValue'``
+ [ ] create request: ``TLINK_FULL_PATH = 'tl.getFullPath'``
+ [ ] create request: ``TLINK_EXEC_DELETE = 'tl.deleteExecution'``
+ [x] create request: ``TPROJECTS = 'tl.getProjects'`` https://github.com/netzulo/qatestlink/commit/796a8243902cedc776ec94681f38b422ea6eddbf
+ [x] create request: ``TPROJECT_BY_NAME = 'tl.getTestProjectByName'`` https://github.com/netzulo/qatestlink/pull/13/commits/ec947d7538f16d2ab5d056201fa9c2d23e60ee18
+ [x] create request: ``TPROJECT_TEST_PLANS = 'tl.getProjectTestPlans'`` https://github.com/netzulo/qatestlink/commit/aeedb0ee42db107b259e6bb94010b93177db069e
+ [ ] create request: ``TPROJECT_TSUITES_FIRST_LEVEL = 'tl.getFirstLevelTestSuitesForTestProject'`` https://github.com/netzulo/qatestlink/pull/15/commits/0936e86cb43e443963cd9531c2c55bb8aec9eac6
+ [ ] create request: ``TPLAN_BY_NAME = 'tl.getTestPlanByName'`` https://github.com/netzulo/qatestlink/pull/16/commits/d7daea46648b6f0b01d6bb4c8a4d4a6621ff6896
+ [ ] create request: ``TPLAN_PLATFORMS = 'tl.getTestPlanPlatforms'`` https://github.com/netzulo/qatestlink/commit/295ca3d2d6dd67d002bb0f7e09798e25387f6315
+ [ ] create request: ``TPLAN_TOTALS = 'tl.getTotalsForTestPlan'`` https://github.com/netzulo/qatestlink/pull/35/commits/2d3314b630f36ceb3d268fa1525c976a75939040
+ [ ] create request: ``TPLAN_BUILDS = 'tl.getBuildsForTestPlan'`` https://github.com/netzulo/qatestlink/pull/18/commits/40c22e2339146012cdd73bee4bdf9bb1f3c78139
+ [ ] create request: ``TPLAN_BUILD_LATEST = 'tl.getLatestBuildForTestPlan'`` https://github.com/netzulo/qatestlink/pull/34/commits/da5f5ba181eaaa4973dd2ac9f1586e70ca0a352f
+ [ ] create request: ``TPLAN_TSUITES = 'tl.getTestSuitesForTestPlan'``  https://github.com/netzulo/qatestlink/commit/0cf6604b5788b5c435c529ae936733c668b922cd
+ [ ] create request: ``TPLAN_TCASES = 'tl.getTestCasesForTestPlan'`` https://github.com/netzulo/qatestlink/commit/c9b2638cb1aa7fdcea29fecd3b335a1eb3f7f290
+ [ ] create request: ``TSUITE_TSUITES = 'tl.getTestSuitesForTestSuite'`` https://github.com/netzulo/qatestlink/pull/36/commits/4e33a0ed25d35b210b6278a6cc2eb190932fd099
+ [ ] create request: ``TSUITE_BY_ID = 'tl.getTestSuiteByID'`` https://github.com/netzulo/qatestlink/pull/25/commits/40b5c294b205de9fba42b92f9f55867b95f3565c
+ [ ] create request: ``TCASE_REPORT_RESULT = 'tl.reportTCResult'`` https://github.com/netzulo/qatestlink/pull/43/commits/eb1c0c8b2ec1f98b5dbce7095076e33c04fe5a1a
+ [ ] ~create request: ``TCASE_EXEC_RESULT = 'tl.setTestCaseExecutionResult'``~ **Just call to 'tl.reportTCResult', no sense develop this**
+ [ ] create request: ``TCASE_ID_BY_NAME = 'tl.getTestCaseIDByName'`` https://github.com/netzulo/qatestlink/pull/37/commits/9979af10688bdc446bfc3582d246dbba5d5f57ad
+ [ ] create request: ``TCASE_BY_IDS = 'tl.getTestCase'`` https://github.com/netzulo/qatestlink/pull/33/commits/7bfff6819101a3a6abdd8ec43ccd070d1862d999
+ [ ] create request: ``TLINK_USER_EXIST = 'tl.doesUserExist'`` https://github.com/netzulo/qatestlink/pull/38/commits/88780fd59f09f7718136673a66dce778869e0168
+ [x] create request: ``TLINK_CHECK_DEV_KEY = 'tl.checkDevKey'`` https://github.com/netzulo/qatestlink/commit/21adff3356086a3ed37f9c70e291579673d233c8
+ [ ] create request: ``TLINK_ABOUT = 'tl.about'`` https://github.com/netzulo/qatestlink/commit/47f51c6917d17bac04d1841b5a198a4f1d37145b
+ [ ] ~create request: ``TLINK_TMODE_TOGGLE = 'tl.setTestMode'``~ **NOT full implemented by testlink, will develop at future**
+ [ ] create request: ``TLINK_SAY_HELLO = 'tl.sayHello'`` https://github.com/netzulo/qatestlink/pull/40/commits/f51deb686da8d95da650d6c6fd2f32fb57640f44
+ [ ] create request: ``TLINK_PING = 'tl.ping'`` https://github.com/netzulo/qatestlink/pull/41/commits/01e6827fa71235e1b1c35078fbdb74497beb1e6e
+ [ ] create request: ``TLINK_REPEAT = 'tl.repeat'`` https://github.com/netzulo/qatestlink/pull/42/commits/47fe30b715fae360c3bb806db018c90824f7900f

## Reviewers _only_

+ CIs will be tested here: https://github.com/netzulo/testlink-tests/pull/2
+ You can exec tests with ``python setup.py test``
