### ISSUE TITLE
Testplan for all Web User Interface

### ISSUE THREAD

**Issue by netzulo** [TestLinkOpenSourceTRMS/testlink-tests#7]
# Description

- Updated package to Pypi package manager : https://pypi.org/project/testlinktests

## TODOs

Version for tests will be : **1.9.19** https://github.com/TestLinkOpenSourceTRMS/testlink-code/tree/1.9.19

+ [ ] create **testsuite** : ``suite_install_configure.py'``
  + [ ] create **testcase** : ``test_install_step_one``
  + [ ] create **testcase** : ``test_install_step_two``
  + [ ] create **testcase** : ``test_install_step_three``
  + [ ] create **testcase** : ``test_install_step_four``
+ [x] create **testsuite** : ``suite_login.py'``
  + [x] create **testcase** : ``test_login_loads``
  + [x] create **testcase** : ``test_login_ok``
  + [x] create **testcase** : ``test_login_ko`` (*low priority for this*)
  + [ ] create **testcase** : ``test_logout_ok`` (*low priority for this*)
+ [x] create **testsuite** : ``suite_dashboard.py'``
  + [x] create **testcase** : ``test_index_loads``
  + [ ] create **testcase** : ``test_index_menu_top``
  + [ ] create **testcase** : ``test_index_menu_left``
  + [ ] create **testcase** : ``test_index_menu_right``
  + [ ] create **testcase** : ``test_``

## Reviewers _only_

+ CIs will be tested here: https://github.com/netzulo/testlink-tests/pull/
+ You can exec tests with ``python setup.py test``
